name: quoter
description: "Get Random Quotes For Your Captions and Posts"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts:
  card_swiper:
  http:
  loading_animation_widget:
  top_snackbar_flutter:
  flutter_dotenv: ^5.2.1
  flip_card: ^0.7.0
  haptic_feedback: ^0.5.1+1
  lottie: ^3.3.1
  path_provider: ^2.0.15
  share_plus: ^11.0.0
  permission_handler: ^12.0.0+1
  auto_size_text: ^3.0.0
  flutter_bloc: ^9.1.1
  vibration: ^3.1.3
  rive: ^0.13.20
  hive_flutter: ^1.1.0
  hive:
  go_router: ^15.1.2
  modals: ^1.0.0+1
  equatable: ^2.0.7
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  screenshot: ^3.0.0
  firebase_core: ^3.13.1
  firebase_ai: ^2.0.0
  hugeicons: ^0.0.11
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner:
  hive_generator:
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - .env
     - assets/
     - assets/rive/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  color: "#13293D"
  image: assets/icons/logo.png
  android_12:
